### ISSUE TITLE
gleap_sdk: ^7.0.0 onwards has an error during flutter build apk.

### ISSUE THREAD

**Issue by sohyuyuan** [GleapSDK/Flutter-SDK#3] opened 2022-07-28 08:41 UTC
Below are the results using different gleap_sdk versions:
- gleap_sdk: ^6.4.8:
<img width="1137" alt="Screenshot 2022-07-28 at 4 32 52 PM" src="https://user-images.githubusercontent.com/57253441/181460347-eb44fbc0-7d8f-4419-ad95-8161555cc2e5.png">

- gleap_sdk: ^7.0.0 onwards:
<img width="1488" alt="Screenshot 2022-07-28 at 4 26 03 PM" src="https://user-images.githubusercontent.com/57253441/181460525-19cd74aa-80f5-42d6-9cd6-e3562dd06e6e.png">

Error Log:
FAILURE: Build failed with an exception.

     * What went wrong:
     Execution failed for task ':gleap_sdk:verifyReleaseResources'.
     > A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
     > Android resource linking failed
     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:3:5-94: AAPT: error: resource android:color/system_neutral1_1000 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:4:5-94: AAPT: error: resource android:color/system_neutral1_900 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:5:5-93: AAPT: error: resource android:color/system_neutral1_0 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:6:5-94: AAPT: error: resource android:color/system_neutral1_800 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:7:5-94: AAPT: error: resource android:color/system_neutral1_700 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:8:5-94: AAPT: error: resource android:color/system_neutral1_600 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:9:5-94: AAPT: error: resource android:color/system_neutral1_500 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:10:5-94: AAPT: error: resource android:color/system_neutral1_400 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:11:5-94: AAPT: error: resource android:color/system_neutral1_300 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:12:5-94: AAPT: error: resource android:color/system_neutral1_200 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:13:5-94: AAPT: error: resource android:color/system_neutral1_100 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:14:5-93: AAPT: error: resource android:color/system_neutral1_50 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:15:5-93: AAPT: error: resource android:color/system_neutral1_10 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:16:5-102: AAPT: error: resource android:color/system_neutral2_1000 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:17:5-102: AAPT: error: resource android:color/system_neutral2_900 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:18:5-101: AAPT: error: resource android:color/system_neutral2_0 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:19:5-102: AAPT: error: resource android:color/system_neutral2_800 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:20:5-102: AAPT: error: resource android:color/system_neutral2_700 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:21:5-102: AAPT: error: resource android:color/system_neutral2_600 not found.

     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/0480e81762638a9be8143ebfaccdde78/transformed/material-1.5.0/res/values-v31/values-v31.xml:22:5-102: AAPT: error: resource android:color/system_neutral2_500 not found.

Flutter Doctor:

> flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-arm, locale en-MY)
    • Flutter version 3.0.5 at /Users/sohyuyuan/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/sohyuyuan/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134
[✓] HTTP Host Availability
    • All required HTTP hosts are available
• No issues found!

**Comment by niklasfessler** [comment] 2022-07-28 08:45
Hey @sohyuyuan ,

let me check this issue for you. Can you give me some more information about your android config. What targetSdkVersion are you using? (e.g. 30, 31?)

Best Regards,

Niklas

**Comment by sohyuyuan** [comment] 2022-07-28 08:50
Hi @niklasfessler, the targetSdkVersion is 33.

> defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.applicationid"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 21
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

**Comment by niklasfessler** [comment] 2022-08-01 08:27
Hey @sohyuyuan,

we have released a new flutter version to tackle this issue. This issue was caused by library incompatibilities. This is resolved in version:

### **7.0.12** 🎉

Please let me know if we can close this issue 😀

**Comment by sohyuyuan** [comment] 2022-08-02 01:43
Thank you @niklasfessler, the issue with material-1.5.0 is resolved.

However, there is a new error occurred.

<img width="1473" alt="Screenshot 2022-08-02 at 9 40 47 AM" src="https://user-images.githubusercontent.com/57253441/182273649-ce69a01a-54f0-4088-8ba3-180e42972443.png">

Error Log:
>* What went wrong:
> Execution failed for task ':gleap_sdk:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/sohyuyuan/.gradle/caches/transforms-3/5e083c06c9925c2309f02468fc66e376/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by sohyuyuan** [comment] 2022-08-03 05:44
Hi @niklasfessler, the issue above was fixed after I update the gleap_sdk to 7.0.13.

I will close the issue, thanks.

**Closed** 2022-08-03 05:45 UTC
